name: DokuWiki Default Tasks
permissions: read-all|write-all
on:
  push:
  pull_request:
  schedule:
    - cron: '10 1 2 * *'


jobs:
  all:
    uses: dokuwiki/github-action/.github/workflows/all.yml@main
